export const ADD_PRODUCT = "ADD_PRODUCT/PRODUCT_REDUCER";
export const ADD_PRODUCTS_DATA = "ADD_PRODUCTS_DATA/PRODUCT_REDUCER";
export const DELETE_PRODUCT_AND_COMMENTS =
  "DELETE_PRODUCT/PRODUCT_REDUCER_AND_COMMENTS_REDUCER";
export const EDIT_COMMENT = "EDIT_COMMENT/COMMENTS_REDUCER";
export const ADD_COMMENT = "ADD_COMMENT/COMMENTS_REDUCER";
export const DELETE_COMMENT = "DELETE_COMMENT/COMMENTS_REDUCER";
export const ADD_COMMENTS_DATA = "ADD_COMMENTS_DATA/COMMENTS_REDUCER";
