export const ADD_PRODUCT_DATA = "ADD_PRODUCT_DATA/PRODUCT_REDUCER";
export const ADD_PRODUCT = "ADD_PRODUCT/PRODUCT_REDUCER";
export const EDIT_PRODUCT = "EDIT_PRODUCT/PRODUCT_REDUCER";
export const DELETE_PRODUCT = "DELETE_PRODUCT/PRODUCT_REDUCER";


export const ADD_COMMENT_DATA = "ADD_COMMENT_DATA/COMMENTS_REDUCER";
export const ADD_COMMENT = "ADD_COMMENT/COMMENTS_REDUCER";
export const EDIT_COMMENT = "EDIT_COMMENT/COMMENTS_REDUCER";
export const DELETE_COMMENT = "DELETE_COMMENT/COMMENTS_REDUCER";


