export const ADD_PRODUCTS = "ADD_PRODUCTS/PRODUCT_REDUCER";
export const DELETE_PRODUCT = "DELETE_PRODUCT/PRODUCT_REDUCER";
export const VISIBILITY_MODAL_WINDOW = "VISIBILITY_MODAL_WINDOW/MODAL_REDUCER";
